modules.exports = {
  abs: [
    "Bicycle Crunches",
    "Cable Oblique Twists",
    "Hanging Knee Raise",
    "Hanging Leg Raise",
    "Lying Leg Raise",
    "Machine Crunch",
    "Rope Crunch",
    "V-Up",
  ],
  back_horizontal: [
    "Barbell Bent-Over Row",
    "Chest Supported Row",
    "Dumbbell Bent-Over Row",
    "Incline Dumbbell Row",
    "Inverted Row",
    "Machine Chest Supported Row",
    "One-Arm Dumbbell Row",
    "Seal Row",
    "Seated Cable Row",
    "T-Row",
  ],
  back_vertical: [
    "Assisted Pullup (Neutral grip)",
    "Assisted Pullup (Normal grip)",
    "Assisted Pullup (Underhand grip)",
    "Assisted Pullup (Wide grip)",
    "Diagonal Iliac Pulldown",
    "Dumbbell Pullover",
    "Lat Prayer",
    "Pulldown (Neutral grip)",
    "Pulldown (Normal grip)",
    "Pulldown (Underhand grip)",
    "Pulldown (Wide grip)",
    "Pullup (Neutral grip)",
    "Pullup (Normal grip)",
    "Pullup (Underhand grip)",
    "Pullup (Wide grip)",
  ],
  biceps: {},
  calves: {},
  chest: {},
  delts: {},
  forearms: {},
  glutes: {},
  hamstrings: {},
  neck: {},
  quads: {},
  traps: {},
  triceps: {},
};
