modules.exports = {
  abs: [
    "Bicycle Crunches",
    "Cable Oblique Twists",
    "Hanging Knee Raise",
    "Hanging Leg Raise",
    "Lying Leg Raise",
    "Machine Crunch",
    "Rope Crunch",
    "V-Up",
  ],
  back_horizontal: [
    "Barbell Bent-Over Row",
    "Chest Supported Row",
    "Dumbbell Bent-Over Row",
    "Incline Dumbbell Row",
    "Inverted Row",
    "Machine Chest Supported Row",
    "One-Arm Dumbbell Row",
    "Seal Row",
    "Seated Cable Row",
    "T-Row",
  ],
  back_vertical: {},
  biceps: {},
  calves: {},
  chest: {},
  delts: {},
  forearms: {},
  glutes: {},
  hamstrings: {},
  neck: {},
  quads: {},
  traps: {},
  triceps: {},
};
