export default {
  Abs: [
    "Bicycle Crunches",
    "Cable Oblique Twists",
    "Hanging Knee Raise",
    "Hanging Leg Raise",
    "Lying Leg Raise",
    "Machine Crunch",
    "Rope Crunch",
    "V-Up",
  ],
  "Back (Horizontal)": [
    "Barbell Bent-Over Row",
    "Chest Supported Row",
    "Dumbbell Bent-Over Row",
    "Incline Dumbbell Row",
    "Inverted Row",
    "Machine Chest Supported Row",
    "One-Arm Dumbbell Row",
    "Seal Row",
    "Seated Cable Row",
    "T-Row",
  ],
  "Back (Vertical)": [
    "Assisted Pullup (Neutral grip)",
    "Assisted Pullup (Normal grip)",
    "Assisted Pullup (Underhand grip)",
    "Assisted Pullup (Wide grip)",
    "Diagonal Iliac Pulldown",
    "Dumbbell Pullover",
    "Lat Prayer",
    "Pulldown (Neutral grip)",
    "Pulldown (Normal grip)",
    "Pulldown (Underhand grip)",
    "Pulldown (Wide grip)",
    "Pullup (Neutral grip)",
    "Pullup (Normal grip)",
    "Pullup (Underhand grip)",
    "Pullup (Wide grip)",
  ],
  Biceps: [
    "Barbell Curl",
    "Bayesian Curl",
    "Cable Curl",
    "Cable EZ Bar Curl",
    "Dumbbell Curl",
    "Dumbbell Single Arm Dumbbell Curl",
    "Dumbbell Spider Curl",
    "EZ Bar Curl",
    "EZ Bar Preacher Curl",
    "EZ Bar Spider Curl",
    "Hammer Curl",
    "Incline Dumbbell Curl",
    "Machine Preacher Curl",
    "Pelican Curl",
    "Pinwheel Curl",
    "Rope Hammer Curl",
  ],
  Calves: [
    "Donkey Calf Raise",
    "Leg Press Calves",
    "Seated Calf Raise",
    "Standing Calf Raises",
  ],
  Chest: [],
  Delts: [],
  Forearms: [],
  Glutes: [],
  Hamstrings: [],
  Neck: [],
  Quads: [],
  Traps: [],
  Triceps: [],
};
