export default {
  Abs: [
    "Bicycle Crunches",
    "Cable Oblique Twists",
    "Hanging Knee Raise",
    "Hanging Leg Raise",
    "Lying Leg Raise",
    "Machine Crunch",
    "Rope Crunch",
    "V-Up",
  ],
  "Back (Horizontal)": [
    "Barbell Bent-Over Row",
    "Chest Supported Row",
    "Dumbbell Bent-Over Row",
    "Incline Dumbbell Row",
    "Inverted Row",
    "Machine Chest Supported Row",
    "One-Arm Dumbbell Row",
    "Seal Row",
    "Seated Cable Row",
    "T-Row",
  ],
  "Back (Vertical)": [
    "Assisted Pullup (Neutral grip)",
    "Assisted Pullup (Normal grip)",
    "Assisted Pullup (Underhand grip)",
    "Assisted Pullup (Wide grip)",
    "Diagonal Iliac Pulldown",
    "Dumbbell Pullover",
    "Lat Prayer",
    "Pulldown (Neutral grip)",
    "Pulldown (Normal grip)",
    "Pulldown (Underhand grip)",
    "Pulldown (Wide grip)",
    "Pullup (Neutral grip)",
    "Pullup (Normal grip)",
    "Pullup (Underhand grip)",
    "Pullup (Wide grip)",
  ],
  Biceps: [
    "Barbell Curl",
    "Bayesian Curl",
    "Cable Curl",
    "Cable EZ Bar Curl",
    "Dumbbell Curl",
    "Dumbbell Single Arm Dumbbell Curl",
    "Dumbbell Spider Curl",
    "EZ Bar Curl",
    "EZ Bar Preacher Curl",
    "EZ Bar Spider Curl",
    "Hammer Curl",
    "Incline Dumbbell Curl",
    "Machine Preacher Curl",
    "Pelican Curl",
    "Pinwheel Curl",
    "Rope Hammer Curl",
  ],
  Calves: [
    "Donkey Calf Raise",
    "Leg Press Calves",
    "Seated Calf Raise",
    "Standing Calf Raise",
  ],
  Chest: [
    "Assisted Dips (Chest)",
    "Barrel Press (Flat)",
    "Barrel Press (Incline)",
    "Barbell Bench Press (Decline)",
    "Barbell Bench Press (Flat)",
    "Barbell Bench Press (Incline)",
    "Cable Flye",
    "Cable Flye (Underhand)",
    "Dips (Chest)",
    "Dumbbell Bench Press (Decline)",
    "Dumbbell Bench Press (Flat)",
    "Dumbbell Bench Press (Incline)",
    "Dumbbell Chest Flye (Decline)",
    "Dumbbell Chest Flye (Flat)",
    "Dumbbell Chest Flye (Incline)",
    "Larsen Press",
    "Machine Chest Press",
    "Machine Chest Press (Incline)",
    "Pec Deck Flye",
    "Pushup",
    "Pushup (Deficit)",
    "Ring Pushup",
    "Ring Flye",
  ],
  Delts: [
    "Arnold Press",
    "Barbell Front Raise",
    "Barbell Overhead Press (Seated)",
    "Barbell Overhead Press (Standing)",
    "Barbell Upright Row",
    "Cable Egyptian Raise",
    "Cable Lateral Raise",
    "Cable Rear Delt Flye",
    "Cable Upright Row",
    "Dumbbell Egyptian Lateral Raise",
    "Dumbbell Front Raise",
    "Dumbbell Lateral Raise",
    "Dumbbell Overhead Press (Seated)",
    "Dumbbell Overhead Press (Standing)",
    "Dumbbell Upright Row",
    "Dumbbell Rear Delt Flye",
    "Face Pull",
    "Machine Shoulder Press",
    "Machine Lateral Raise",
    "Pec Deck Rear Delt Flye",
    "Skiers",
  ],
  Forearms: [
    "Barbell Wrist Curl",
    "Barbell Reverse Curl",
    "Cable Wrist Curl",
    "Cable Reverse Curl",
    "Dumbbell Wrist Curl",
    "Dumbbell Reverse Curl",
    "EZ Bar Reverse Curl",
  ],
  Glutes: [
    "Barbell Hip Thrust",
    "Barbell Reverse Lunge",
    "Barbell Walking Lunge",
    "Cable Pull Through",
    "Dumbbell Reverse Lunge",
    "Dumbbell Split Squat (Glutes)",
    "Dumbbell Walking Lunge",
    "Machine Hip Thrust",
    "Single-leg Hip Thrust",
    "Smith Machine Glute Kickback",
  ],
  Hamstrings: [
    "Back Extension",
    "Barbell Stiff-leg Deadlift",
    "Barbell Romanian Deadlift",
    "Dumbbell Stiff-leg Deadlift",
    "Dumbbell Romanian Deadlift",
    "Glute Ham Raise",
    "Good Morning",
    "Lying Leg Curl",
    "Seated Leg Curl",
  ],
  Neck: ["Lateral Neck Flexion", "Neck Curl", "Neck Extension"],
  Quads: [
    "Back Squat (High Bar)",
    "Back Squat (Low Bar)",
    "Belt Squat",
    "Bulgarian Split Squat",
    "Dumbbell Split Squat (Quads)",
    "Front Squat",
    "Goblet Squat",
    "Hack Squat",
    "Leg Extension",
    "Leg Press",
    "Smith Machine Hack Squat",
  ],
  Traps: [
    "Barbell Shrug",
    "Barbell Bent Shrug",
    "Dumbbell Shrug",
    "Dumbbell Bent Shrug",
  ],
  Triceps: [
    "Assisted Dips (Tricep)",
    "Barbell Tricep Overhead Extension",
    "Cable Tricep Pushdown",
    "Dips (Tricep)",
    "Dumbbell Skullscrusher",
    "Dumbbell Tricep Overhead Extension",
    "EZ Bar Skullcrusher",
    "EZ Bar Tricep Overhead Extension",
    "JM Press",
    "Rope Tricep Pushdown",
    "Rope Tricep Overhead Extension",
  ],
};
